version: "3"

volumes:
  publy_database:

services:
  database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - publy_database:/var/lib/postgresql/data
